/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CommentStatus = "pending" | "published";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type PostStatus = "draft" | "published";

export type TestimonialStatus = "draft" | "published";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Comments {
  authorEmail: string | null;
  authorName: string;
  content: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  parentId: string | null;
  postId: string;
  status: Generated<CommentStatus>;
}

export interface Posts {
  content: Generated<string>;
  createdAt: Generated<Timestamp>;
  excerpt: string | null;
  featuredImage: string | null;
  id: Generated<string>;
  publishedAt: Timestamp | null;
  slug: string;
  status: Generated<PostStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  wpOriginalId: number | null;
}

export interface PostTags {
  postId: string;
  tagId: string;
}

export interface Tags {
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface Testimonials {
  author: string;
  content: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  publishedAt: Timestamp | null;
  status: Generated<TestimonialStatus>;
}

export interface Works {
  content: Generated<string>;
  createdAt: Generated<Timestamp>;
  excerpt: string | null;
  featuredImage: string | null;
  id: Generated<string>;
  slug: string;
  status: Generated<PostStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  wpOriginalId: number | null;
}

export interface DB {
  comments: Comments;
  posts: Posts;
  postTags: PostTags;
  tags: Tags;
  testimonials: Testimonials;
  works: Works;
}
